version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: updating npm...
          command: npm i -g npm
      - run:
          name: installing dev dependencies...
          command: npm ci
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
              - ./node_modules
      - run:
          name: checking coverage...
          command: npm run cover
      - run:
          name: reporting to codecov...
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: linting...
          command: npm run lint
      - run:
          name: building modern & legacy packages...
          command: npm run build
